(custom-set-variables
 '(auto-save-default nil)
 '(buffer-file-coding-system (quote raw-text-dos) t)
 '(case-fold-search nil)
 '(column-number-mode t)
 '(default-frame-alist (quote ((menu-bar-lines . 1) (width . 90))) t)
 '(default-gutter-position (quote top))
 '(default-toolbar-position (quote top))
 '(delete-key-deletes-forward t)
 '(ecb-options-version "2.24")
 '(efs-ftp-program-args (quote ("-L" "-u")))
 '(efs-ftp-prompt-regexp "^.*> *")
 '(efs-use-passive-mode nil)
 '(fast-lock-mode nil nil (fast-lock))
 '(fill-column 80)
 '(global-font-lock-mode t nil (font-lock))
 '(gnuserv-frame t)
 '(gutter-buffers-tab-enabled t)
 '(gutter-buffers-tab-visible-p t)
 '(indent-tabs-mode nil)
 '(initsplit-customizations-alist (quote (("^c-macro-preprocessor$" "~/.emacs.common/paths.el" nil) ("^\\(emacs-wiki\\|planner\\|remember\\)" "~/.emacs.common/planner_init.el" nil) ("^c-" "~/.emacs.common/c-mode_init.el" nil))))
 '(initsplit-sort-customizations t)
 '(lazy-lock-mode nil nil (lazy-lock))
 '(lazy-shot-mode nil nil (lazy-shot))
 '(line-number-mode t)
 '(make-backup-files nil)
 '(next-line-add-newlines nil)
 '(package-get-always-update t)
 '(paren-mode (quote paren) nil (paren))
 '(pop-up-windows t)
 '(popper-install-when-load nil nil (popper))
 '(progress-feedback-style (quote small))
 '(require-final-newline t)
 '(sentence-end-double-space nil)
 '(tab-width 4)
 '(toolbar-visible-p nil))
(custom-set-faces
 '(default ((t (:background "peachpuff"))) t)
 '(highline-face ((t (:background "grey90")))))
(put 'narrow-to-region 'disabled nil)
